[project]
name = "E0230-CMO-2025"
version = "0.1.1"
description = "Algorithms"
authors = [{ name = "Ashrith Sagar", email = "ashrithy@iisc.ac.in" }]
readme = "./README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "rich>=14.2.0",
    "scipy>=1.16.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["jupyter>=1.1.1", "pytest>=8.4.2", "pytest-memray>=1.8.0"]

[tool.hatch.build.targets.wheel]
packages = ["src"]
