[project]
name = "cmo"
version = "0.1.2"
description = "Optimisation algorithms"
authors = [{ name = "Ashrith Sagar", email = "ashrithy@iisc.ac.in" }]
readme = "./README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "rich>=14.2.0",
    "scipy>=1.16.2",
]

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["jupyter>=1.1.1", "pytest>=8.4.2", "pytest-memray>=1.8.0"]
